parameters:
  cronjob.service: MH1\CronBundle\Service\DoctrineCronJobService
  cronjob.log.service: MH1\CronBundle\Service\DoctrineCronJobLogService
  cronjob.check_interval: 1000
  cronjob.execution_time_zone: null
  cronjob.lock_prefix: ''
  cronjob.php_executable_path: null
